# Configuration file for PerfMTK Daemon
# Format: package_name=energy_profile[;directives]

# Default global profile when no application from the list is in the foreground
DEFAULT_PROFILE=balanced
SCREEN_OFF_PROFILE=powersave+
APP_DEBOUNCE_MS=2000

com.activision.callofduty.shooter=performance;gbe=1;render_boost=1;fps=120;thermal=off;touch=game
com.antutu.ABenchMark=performance;thermal=off
com.antutu.benchmark.full=performance;gbe=1;thermal=off
com.facebook.katana=powersave
com.futuremark.dmandroid.application=performance;thermal=off
com.gameloft.android.ANMP.GloftA9HM=performance;gbe=1;render_boost=1;fps=90;thermal=off;touch=game
com.google.android.apps.youtube.music=powersave
com.google.android.youtube=powersave
com.instagram.android=powersave
com.kurogame.wutheringwaves.global=performance;gbe=1;charge_bypass=on;render_boost=1;fps=60;thermal=off;touch=game
com.primatelabs.geekbench6=performance;fps=60;thermal=off
com.tencent.ig=performance;gbe=1;charge_bypass=on;render_boost=1;fps=120;thermal=off;touch=game
com.treeteam.touchsampling=performance;fps=120;touch=game
com.zhiliaoapp.musically=powersave
