# Configuration file for PerfMTK Daemon
# Format: package_name=energy_profile

# Default global profile when no application from the list is in the foreground
DEFAULT_PROFILE=balanced

SCREEN_OFF_PROFILE=powersave
APP_DEBOUNCE_MS=3000

# Games with automated thermal throttling bypass
com.kurogame.wutheringwaves.global=performance;thermal=off;touch=game
com.tencent.ig=performance;thermal=off;touch=game
